### ISSUE TITLE
sigex.ivarpar

### ISSUE THREAD

**Issue by duncanelliott** [tuckermcelroy/sigex#2]
function sigex.ivarpar in the examples provided but not available in installed package ie last line of

## preliminary analysis
ar.fit <- ar.yw(diff(ts(ndc[2:T,])))
p.order <- ar.fit$order
par.yw <- aperm(ar.fit$ar,c(2,3,1))
covmat.yw <- getGCD(ar.fit$var.pred,2)
var.out <- sigex.ivarpar(par.yw)

**Comment by tuckermcelroy** [comment]
Sorry, didn't see this!
sigex.ivarpar has been deprecated in newer code.  replace last line with
var.out <- var2.par2pre(par.yw)
var2.par2pre is new function used to control VAR parameterization.
